const initialState = {
    dong: '',
    hosil: '',
    floor: '',
    dong_name: '',
    ho_name: '',
    floorname: '',
    storeofficebuildingfloor: '',

    dangi: '',
    dangijibunaddress: '',
    dangiroadaddress: '',
    jibunsimple: '',
    x: '',
    y: '',
    name: '',
    phone: '',
    maemultype: '',

    maemulname: '',
    jeonyongdimension: '',
    jeonyongpyeong: '',
    supplydimension: '',
    supplypyeong: '',
    selltype: '',
    sellprice: '',
    monthsellprice: '',
    managecost: '',
    is_immediate_ibju: '',
    ibju_specifydate: '',
    exclusive_periods: '',
    companyid: '',
    requestmemid: '',
    include_managecost: '',

    is_current_biz_job: '',
    current_biz_job: '',
    ismanagementcost: '',
    officetelusetype: '',
    isrightprice: ''
};